export { default as airplane } from './glyphicons-basic-39-airplane.svg'
export { default as home } from './glyphicons-basic-21-home.svg'
export { default as star } from './glyphicons-basic-49-star.svg'
export { default as starHalf } from './glyphicons-basic-543-star-half.svg'
export { default as train } from './glyphicons-basic-15-train.svg'
