name: Main

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v3

      - 
        # https://github.com/actions/setup-node
        name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20.2.0'

      - 
        # https://github.com/pnpm/action-setup
        name: Install PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.5.1
          run_install: false

      -
        name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      -
        # https://github.com/actions/cache
        uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      -
        name: Install dependencies
        run: |
          pnpm install

      -
        name: Build All The Things
        run: |
          pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: apps/web/dist
          branch: gh-pages
